# Generated by Django 2.1.2 on 2018-10-20 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Distance',
            new_name='DbDistance',
        ),
    ]
